version: '3'
services:
  mysql:
    container_name: bancoChefware
    image: mysql:latest
    restart: always 
    environment:
      MYSQL_ROOT_PASSWORD: 9090
      MYSQL_USER: root
      MYSQL_DATABASE: chefware
    volumes:
        - db_data:/var/lib/mysql
    ports:
        - "3306:3306"
volumes:
  mysql_data:
